name: PluginMC
version: '1.0-SNAPSHOT'
authors: [LeFisc_]
main: fr.api.pluginmc.Main
api-version: 1.20
commands:
  money:
    description: Money
    permission: money.use
  test:
    description: Ceci est une commande de test
    permission: test.use
  alert:
    description: Ceci est un broadcast custom
    permission: bc.use
  monster:
    description: Monster
    permission: bc.use
    usage: "/monster"
  stats:
    description: stats
    permission: stats.use
    usage: "/stats"
  shop:
    description: shop
    permission: shop.use
    usage: "/shop"